"""What SOVERYN claims to be running — declared, so it can be checked.

On 2026-08-07 `atticus.historysledger.com` was returning 404 and had been for an
unknown period. Its systemd unit had never been installed. Nothing detected this,
and no amount of checking would have: **Atticus was not in any registry.** Its
failure mode was not "a check failed" — it was "nothing knew it was supposed to
exist."

That is the gap this module closes. `RUNTIME_SERVICES` in `soveryn.config.runtime`
declares six internal daemons. The things the outside world actually touches —
the curator, the compliance product, the public sites, the agent front doors —
were declared nowhere, so they were unwatchable by construction.

Three rules this table exists to enforce:

1. **Declare the surface or it cannot be seen.** A surface absent from this table
   is not "healthy"; it is invisible, which is worse.

2. **Probe function, not status.** `systemctl is-active` reported the Telegram
   bridge as active for eight days while it logged 91,560 HTTP 409s and delivered
   nothing. Status is not evidence of work. Where a functional probe is possible
   this table specifies one.

3. **UNKNOWN is not HEALTHY.** A probe that cannot run returns UNKNOWN and says
   so. Every incident this week — the audit tool reading four stores of five,
   Ares reading a failed nvidia-smi as three healthy cards — was absence recorded
   as an all-clear.

`expect` is deliberately conservative: it asserts the surface is doing its job,
not that the job is done well. Correctness is what tests are for.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class Kind(str, Enum):
    UNIT = "unit"          # a systemd unit that must be active
    HTTP = "http"          # an endpoint that must answer
    FUNCTIONAL = "functional"  # an endpoint that must do its actual job
    PUBLIC = "public"      # reachable from the open internet


@dataclass(frozen=True)
class Surface:
    """One thing SOVERYN claims to be running.

    `interval_s` is how long this surface may go unverified before staleness
    alone is a finding. That clock is what catches a surface nobody is checking,
    as distinct from one that is checked and failing.
    """

    name: str
    kind: Kind
    target: str                      # unit name, or URL
    owner: str = "soveryn"           # which agent/product owns it
    interval_s: float = 900.0
    # FUNCTIONAL only: a request that exercises the real path.
    method: str = "GET"
    payload: dict | None = None
    expect_status: int = 200
    expect_contains: str = ""        # substring the response must contain
    # For surfaces whose body is generated by a model. Asserting on wording is a
    # trap: the first version of this table required "rebate" in Atticus's reply
    # and the model said "kickbacks" on 2 runs in 3 — a healthy service reported
    # DOWN two thirds of the time. Assert on SHAPE instead. A non-empty `reply`
    # of reasonable length proves server, guard, backend and corpus all worked,
    # without betting on which synonym came out.
    expect_json_field: str = ""      # this key must exist and be non-empty
    expect_min_chars: int = 0        # ...and be at least this long
    # A surface can be down for a reason. Set when a human has decided so, with
    # the reason — never as a way to silence something inconvenient.
    retired: str = ""
    notes: str = ""


# ── the table ───────────────────────────────────────────────────────────────
#
# Ordered roughly by blast radius: public things a stranger can hit, then the
# products, then internal machinery.

SURFACES: tuple[Surface, ...] = (
    # ── public ────────────────────────────────────────────────────────────
    Surface(
        "soverynintelligence.com", Kind.PUBLIC, "https://soverynintelligence.com/",
        owner="soveryn", interval_s=1800,
        expect_contains="SOVERYN",
        notes="Cloudflare Pages. Served a retracted v2 of the self-knowledge "
              "paper until 2026-08-03 because nothing declared what it should serve.",
    ),
    Surface(
        "atticus", Kind.FUNCTIONAL, "https://atticus.historysledger.com/chat",
        owner="vett", interval_s=1800,
        method="POST",
        payload={"session_id": "surface-probe",
                 "messages": [{"role": "user",
                               "content": "In one sentence: what were Standard Oil's railroad rebates?"}]},
        expect_json_field="reply", expect_min_chars=60,
        notes="The curator of History's Ledger. RUNS ON THE SPARK (127.0.0.1:8500 "
              "there), reachable only through the pondwright cloudflared tunnel — "
              "so the public URL is the only probe point from the tower.\n"
              "First declared here as GET / and reported DOWN. It was NOT down. "
              "Atticus serves only POST /chat and its 404 on GET / is correct "
              "behaviour; a duplicate service was installed on the tower before "
              "anyone checked. Probe the contract a service actually offers, or "
              "the monitor invents outages — the same 'absence read as fact' this "
              "package exists to prevent, committed while building it.",
    ),
    Surface(
        "soveryn-agent", Kind.FUNCTIONAL, "https://ask.soverynintelligence.com/chat",
        owner="soveryn", interval_s=1800,
        method="POST",
        payload={"session_id": "surface-probe",
                 "messages": [{"role": "user",
                               "content": "In one sentence, what is SOVERYN?"}]},
        expect_json_field="reply", expect_min_chars=60,
        notes="SENECA, the public front door. On the Spark behind the same "
              "cloudflared tunnel as atticus — if both fail together, suspect the "
              "tunnel, not either service.\n"
              "Like atticus, it serves ONLY POST /chat; GET / correctly returns "
              "404. Declared as GET / first and it read as an outage, which is "
              "the second time in one hour the same wrong assumption produced a "
              "phantom failure. Verify a service's actual contract before "
              "declaring what healthy looks like.",
    ),
    Surface(
        "historysledger.com", Kind.PUBLIC, "https://historysledger.com/",
        owner="vett", interval_s=1800,
    ),
    Surface(
        "shepherd", Kind.HTTP, "http://127.0.0.1:5055/",
        owner="jon", interval_s=900, expect_status=401,
        notes="401 IS the healthy answer — the demo sits behind HTTP Basic. "
              "Expecting 200 here would report a working auth gate as an outage. "
              "This is the LOCAL check; the public path is the surface below.",
    ),
    Surface(
        "shepherdfcc", Kind.PUBLIC, "https://shepherdfcc.com/",
        owner="jon", interval_s=900, expect_status=401,
        notes="The partner-facing address, live 2026-08-07. Path is Cloudflare -> "
              "cloudflared on the SPARK -> CX-7 fabric -> Shepherd on the TOWER at "
              "10.10.10.1:5055, so a failure here can be the tunnel, the fabric or "
              "the app — check `shepherd` above to tell them apart. 401 is healthy.",
    ),
    Surface(
        "pondwright", Kind.PUBLIC, "https://pondwright.com/",
        owner="jon", interval_s=3600,
    ),
    # The three PondWright surfaces on the Spark. Each has a DIFFERENT healthy
    # answer at the root — 401, 404 and 200 respectively — which is precisely
    # why "GET / should be 200" is not a rule that can be applied by default.
    Surface(
        "pondwright-crm", Kind.HTTP, "https://crm.pondwright.com/",
        owner="jon", interval_s=1800, expect_status=401,
        notes="401 is healthy — the CRM is password-gated. Holds real customer "
              "leads; leads.db is git-ignored by stem, not extension.",
    ),
    Surface(
        "pondwright-chat", Kind.FUNCTIONAL, "https://chat.pondwright.com/chat",
        owner="jon", interval_s=1800, method="POST",
        payload={"session_id": "surface-probe",
                 "messages": [{"role": "user",
                               "content": "In one sentence, what do you help with?"}]},
        expect_json_field="reply", expect_min_chars=40,
        notes="The openly-AI intake agent. Never quotes prices. POST /chat only.",
    ),
    Surface(
        "pondwright-estimator", Kind.HTTP, "https://estimator.pondwright.com/",
        owner="jon", interval_s=3600,
        notes="Password-gated PWA; serves a real page at the root. NEVER expose "
              "estimator Step 2 — it is Jon's margin.",
    ),
    Surface(
        "carolinawatergardens", Kind.PUBLIC, "https://carolinawatergardens.com/",
        owner="jon", interval_s=3600,
    ),

    # ── inference ─────────────────────────────────────────────────────────
    Surface(
        "router-blackwell", Kind.HTTP, "http://127.0.0.1:8090/health",
        owner="aetheria", interval_s=300,
        notes="Aetheria alone on the Blackwell.",
    ),
    Surface(
        "router-quadro", Kind.HTTP, "http://127.0.0.1:8091/health",
        owner="soveryn", interval_s=300,
    ),
    Surface(
        "qwen-spark", Kind.HTTP, "http://10.10.10.2:8001/v1/models",
        owner="vett", interval_s=600, expect_contains="qwen36-35b",
        notes="Backend for Vett, Scotty, PondWright, Atticus and Seneca, over "
              "the CX-7 fabric. Was laguna on :8000 until 2026-08-12; "
              "laguna-serve is stopped and disabled, so probing :8000 would "
              "page about a service we took down on purpose.",
    ),
    Surface(
        "embeddings", Kind.HTTP, "http://127.0.0.1:8096/health",
        owner="aetheria", interval_s=600,
    ),

    # ── internal ──────────────────────────────────────────────────────────
    # `/` is vnext's health path. There is no /api/health — probing one that
    # does not exist reports a healthy service as a 404 outage, which is the
    # false-alarm failure mode this whole lane must avoid.
    Surface("vnext", Kind.HTTP, "http://127.0.0.1:5001/",
            owner="soveryn", interval_s=300),
    Surface("heartbeat", Kind.UNIT, "soveryn-heartbeat.service",
            owner="aetheria", interval_s=1800),
    Surface("ares", Kind.UNIT, "soveryn-ares.service", owner="ares"),
    Surface("dream", Kind.UNIT, "soveryn-dream.service", owner="aetheria"),
    Surface("signal-bridge", Kind.UNIT, "soveryn-signal-bridge.service",
            owner="aetheria", interval_s=1800,
            notes="The channel Jon actually uses."),
    Surface("xid-capture", Kind.UNIT, "soveryn-xid-capture.service",
            owner="soveryn", interval_s=3600,
            notes="Forensics for the recurring Blackwell RC-watchdog lock."),

    # ── retired, kept visible on purpose ──────────────────────────────────
    Surface(
        "tg-bridge", Kind.UNIT, "soveryn-tg-bridge.service", owner="soveryn",
        retired="2026-08-07 — Telegram replaced by Signal. Logged 91,560 HTTP "
                "409s in 7 days because the Claude Code telegram plugin polls "
                "the same bot token. Removed from medic.TARGETS, which had been "
                "resurrecting it 42s after every stop.",
        notes="Left in the table rather than deleted so 'deliberately off' is a "
              "recorded state, not an absence someone re-discovers in six months.",
    ),
)

BY_NAME = {s.name: s for s in SURFACES}


def live() -> tuple[Surface, ...]:
    """Surfaces that are expected to be up right now."""
    return tuple(s for s in SURFACES if not s.retired)


def owned_by(agent: str) -> tuple[Surface, ...]:
    return tuple(s for s in live() if s.owner == agent)
